

spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        input:
          destination: creationBookServiceDestination
          group: creationBookServiceGroup
          binder: kafka
        output:
          destination: storeServiceDestination
          group: storeServiceGroup
          binder: kafka
server:
  port: 8051