spring:
  application:
    name: eureka-client

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 35
